version: '2'
services:
  example-postgresql:
    image: postgres:12.1
    # volumes:
    #     - ~/volumes/jhipster/example/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=example
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
